[project]
name = "toml_test"
version = "0.1.0"
author = "Me"
author_email = "your@email.address"
url = "https://godatadriven.com/blog/a-practical-guide-to-setuptools-and-pyproject-toml"
description = "Example package description"
readme = "README.md"
keywords = ["example", "setuptools"]

dependencise = [
    "pandas == 1.4.1"
]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[tool.setuotools]
package_dir = "./src"


